---
- name: installing packages
  hosts: localhost
  connection: local
  become: true
  gather_facts: no
  tasks:
          - name: installing htop
            yum:
                    name: htop
                    

